PROJECT_GITBASE=https://github.com/
PROJECT_GIT_REPO=GEBIT/kubernetes-plugin
JOB_GROUP=gebit-build
JOB_PRODUCT=
JOB_UPSTREAM=[:]
JOB_MAIL_FAILURES=team_dinf@gebit.de
JOB_XVFB=false
JOB_SITE_SEPARATE=false
JOB_MVN_OPTS=-Xmx512M -XX:MaxPermSize=256m 
JOB_INTEGRATION_TRIGGER=false
JOB_DOCKER_LABELS=jenkins-slave-jdk8-maven
JOB_MAVEN=Maven 3.6
JOB_NIGHTLIES=false
